config/routes.rb
Rails.application.routes.draw do

  root :to => "pages#about"
  get 'search', :to => "search#index"
  get '/astronomycatalogue/your_catalogue' => 'astronomical_items#author_index'
  resources :astronomical_items, path: :astronomycatalogue do 
    resources :comments, :only => [:create, :destroy ]
  end
  
  
  resources :users, :only => [:new, :create ]
  

  get '/bookmarks' => 'bookmarks#show'
  post '/bookmarks' => 'bookmarks#new'

  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/login' => 'session#destroy'
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/astronomical_item.rb
class AstronomicalItem < ApplicationRecord
    belongs_to :user, :optional => true
    has_many :bookmarks, :dependent => :destroy
    has_many :comments, :dependent => :destroy
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
    belongs_to :user, :optional => true #REMOVE LATER #use dependant destroy here?
    belongs_to :astronomical_item, :optional => true #REMOVE LATER
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :user, :optional => true #REMOVE LATER
    belongs_to :astronomical_item, :optional => true #REMOVE LATER
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password #research this
    validates :email, :uniqueness => true, :presence => true #research this
    
    has_many :astronomical_items
    has_many :bookmarks, :dependent => :destroy
    has_many :comments, :dependent => :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    before_action :fetch_user
    before_action :set_query

    def set_query
        @query = AstronomicalItem.ransack(params[:q])
    end


    private
    def fetch_user
        @current_user = User.find_by :id => session[:user_id]
        session[:user_id] = nil unless @current_user.present?
    end

    def check_for_login
        redirect_to login_path unless @current_user.present?
    end

    def bookmark_text
        if @bookmark_exists
            return "Remove Bookmark"
        else
            return "Bookmark"
        end
    end

    helper_method :bookmark_text

end

app/controllers/astronomical_items_controller.rb
class AstronomicalItemsController < ApplicationController

  before_action :check_for_login

  def author_index
    @astronomical_items = AstronomicalItem.where(user_id: @current_user.id)
  end
  
  def new
    @astronomical_item = AstronomicalItem.new
  end

  def create

    astronomical_item = AstronomicalItem.new params_astronomical_item
    astronomical_item.user_id = @current_user.id
    if params[:file].present?
      req = Cloudinary::Uploader.upload(params[:file])
      astronomical_item.image = req["public_id"]
      astronomical_item.save
      redirect_to astronomical_item
    else
      flash[:error] = "Please upload an image"
      astronomical_item.delete
      redirect_to new_astronomical_item_path
    end
    
  end


  def edit
    @astronomical_item = AstronomicalItem.find params[:id]
  end

  def update
    astronomical_item = AstronomicalItem.find params[:id]
    astronomical_item.update params_astronomical_item

    if params[:file].present?
      req = Cloudinary::Uploader.upload(params[:file])
      astronomical_item.image = req["public_id"]
      astronomical_item.save
    end
    
    redirect_to astronomical_item
  end

  def index
    @astronomical_items = AstronomicalItem.paginate(page: params[:page], per_page: 10)
  end

  def show
    @astronomical_item = AstronomicalItem.find params[:id]
    @item_author = User.find @astronomical_item.user_id
    @bookmark_exists = Bookmark.where(user_id: @current_user.id, astronomical_item_id: @astronomical_item.id ) == [] ? false : true
  end

  def destroy
    astronomical_item = AstronomicalItem.find params[:id]
    astronomical_item.destroy
    redirect_to astronomical_items_path
  end

  private
  def params_astronomical_item
    params.require(:astronomical_item).permit(:name, :category, :summary, :image)
  end

end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController

    before_action :check_for_login

    def show
        @bookmarked_astronomical_items = []
        @current_user.bookmarks.each do |bookmark|
            @bookmarked_astronomical_items.push(AstronomicalItem.find bookmark.astronomical_item_id)
        end
    end
        
    def new
        bookmark_check = Bookmark.find_by user_id: @current_user.id, astronomical_item_id: params[:astronomical_item_id]
        
        if bookmark_check.nil?
            bookmark = Bookmark.create(:user_id => @current_user.id, :astronomical_item_id => params[:astronomical_item_id])
            @bookmark_exists = true
        else
            bookmark_check.delete
            @bookmark_exists = false
        end
    end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

    def create
        comment = Comment.new comment_params
        if !comment.save
            flash[:notice] = comment.errors.full_messages.to_sentence
        
        end
        redirect_to astronomical_item_path(params[:astronomical_item_id])
    end

    def destroy
        comment = Comment.find params[:astronomical_item_id]
        comment.destroy
        redirect_to astronomical_item_path(params[:id])
    end


    private
    def comment_params
        params.require(:comment).permit(:content, :user_id, :astronomical_item_id )
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

    require 'httparty'

    def about
        @response = HTTParty.get('https://api.nasa.gov/planetary/apod?api_key=cuxOmwpr2KanSuHRAl75GBqxEWjLLqkYA9kBGqj4');
    end

end

app/controllers/search_controller.rb
class SearchController < ApplicationController

  def index
    @query = AstronomicalItem.ransack(params[:q])
    @astronomical_items = @query.result(distinct: true)
  end

end

app/controllers/session_controller.rb
class SessionController < ApplicationController


    def new
    end

    def create
        user = User.find_by :email => params[:email]
        if user.present? && user.authenticate(params[:password])
            session[:user_id] = user.id
            redirect_to root_path
        else
            flash[:error] = "Invalid email or password"
            redirect_to login_path
        end
    end

    def destroy
        session[:user_id] = nil
        redirect_to login_path
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new params_user
    if @user.save
      session[:user_id] = @user.id # add notice for successful creation
      redirect_to root_path
    else
      render :new
    end
  end

  private
  def params_user
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/astronomical_item_helper.rb
module AstronomicalItemHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/astronomical_items/_form.html.erb
<% if flash[:error].present? %>
    <p class="flash_login_error"><%= flash[:error] %></p>
<% end %>

<div class='add_edit_form'>
    <%= form_for(@astronomical_item, :html => { :multipart => true }) do |f| %>

        <%= f.label :name, :class => 'form-label' %>
        <%= f.text_field :name, placeholder: "Object's Name", :required => true, :class => 'form-control' %>

        <%= f.label :category, :class => 'form-label' %>
        <%= f.text_field :category, placeholder: "Main Sequence Star, Gas Giant, etc", :required => true, :class => 'form-control' %>

        <%= f.label :summary, :class => 'form-label' %>
        <%= f.text_area :summary, placeholder: "Brief description of the object", :required => true, :class => 'form-control' %>

        <%= f.label :image, :class => 'form-label' %>
        <%= f.cl_image_upload :image, :required => true, :class => 'form-control' %> 
        <br>
        <br>
        <%= f.submit :class => 'btn btn-primary' %>

    <% end %>
</div>

app/views/astronomical_items/author_index.html.erb
<h2><u>Your Astronomical Objects</u></h2>

<% if @astronomical_items.present?%>
    <div class="table">
        <table class="table table-dark table-striped">
            <thead>
                <th class="table_head">Object Name</th>
                <th class="table_head">Category</th>
            </thead>

            <tbody>
                <% @astronomical_items.each do |astronomical_item| %>
                    <tr>
                        <td> <%= link_to astronomical_item.name, astronomical_item %></td>
                        <td> <%= astronomical_item.category %> </td>
                    </tr>
                <% end %>
            </tbody>
        </table>
    </div>
<% else %>
    <p class="empty_list">You have not added any objects to the catalogue</p>
<% end %>

app/views/astronomical_items/edit.html.erb
<h1><u>Edit Astronomical Item</u></h1>

<%= render :partial => 'form' %>

app/views/astronomical_items/index.html.erb
<h1><u>Astronomical Catalogue</u></h1>

<div class="table">
    <table class="table table-dark table-striped">
        <thead>
            <th class="table_head">Object Name</th>
            <th class="table_head">Category</th>
            <th class="table_head">Author</th>
        </thead>

        <tbody>
            <% @astronomical_items.each do |astronomical_item| %>
                <tr>
                    <td> <%= link_to astronomical_item.name, astronomical_item %></td>
                    <td> <%= astronomical_item.category %> </td>
                    <td> <%= astronomical_item.user.name %> </td>
                </tr>
            <% end %>
        </tbody>
    </table>
</div>

<%= will_paginate @astronomical_items, :class => "digg_pagination" %>

app/views/astronomical_items/new.html.erb
<h1><u>Add to Catalogue</u></h1>


<%= render :partial => 'form' %>

app/views/astronomical_items/show.html.erb
<h1><u><%= @astronomical_item.name %> - <%= @astronomical_item.category %></u></h1>

<p class="summary"><%= @astronomical_item.summary %></p>

<%= cl_image_tag @astronomical_item.image, :class => "feature" if @astronomical_item.image.present? %>
<div class="author_comment_bookmark">
<br>
<p>Added by <%= @item_author.name %></p>

<% if @current_user == @item_author %>
<div class="edit_delete">
    <%= link_to "Edit Entry", edit_astronomical_item_path(@astronomical_item.id), :class => "link-primary" %> |
    <%= link_to "Delete Entry", @astronomical_item, :method => :delete, :data => { :confirm => "Are you sure?" }, :class => "link-primary" %>
</div>
<% end %>
<br>

<div class="bookmark_button">
   <%= button_to bookmark_text, bookmarks_path, params: { astronomical_item_id: @astronomical_item.id  }, :class => "btn btn-primary btn-sm", id: 'bookmark_button', remote: true %>
</div>
<br>
<p> 

<strong>Comments:</strong>
<%= render :partial => "comments/form", params: { astronomical_item_id: @astronomical_item.id  } %>
<br>
<%= render @astronomical_item.comments.order(created_at: :desc) %>
</p>
</div>

app/views/bookmarks/new.js.erb
$("#bookmark_button").attr("value", "<%= bookmark_text %>");

app/views/bookmarks/show.html.erb
<h2><u>Your bookmarks</u></h2>

<% if @bookmarked_astronomical_items.present? %>
<div class="table">
        <table class="table table-dark table-striped">
            <thead>
                <th class="table_head">Object Name</th>
                <th class="table_head">Category</th>
                <th class="table_head">Author</th>
            </thead>

            <tbody>
                <% @bookmarked_astronomical_items.each do |astronomical_item| %>
                    <tr>
                        <td> <%= link_to astronomical_item.name, astronomical_item %></td>
                        <td> <%= astronomical_item.category %> </td>
                        <td> <%= astronomical_item.user.name %> </td>
                    </tr>
                <% end %>
            </tbody>
        </table>
    </div>

<% else %>
    <p class="empty_list">You have not bookmarked any objects</p>
<% end %>

app/views/comments/_comment.html.erb
<article class="comment">
<p>
<small><%= comment.user.name %> - <%= comment.created_at.strftime("%e %b %Y") %>:</small>
</p>
<p>
<%= comment.content %>
</p>
<% if @current_user.id == comment.user.id %>
    <p><small><%= link_to "Delete", astronomical_item_comment_path(comment.id), :method => :delete, :data => { :confirm => "Are you sure?" } %></small></p>
<% end %>
<hr>
</article>

app/views/comments/_form.html.erb
<%#why does :comment work?%>

<%= form_for(:comment, :url => astronomical_item_comments_path(@astronomical_item.id)) do |f|  %> 

    
    <%= f.text_area :content, rows: 3, cols: 30, :required => true, :class => "comment_field" %> 
    <%# <%= f.text_area(:comment, :text, size: "20x30") %> 
    <%= f.hidden_field :user_id, value: @current_user.id %>

    <%= f.hidden_field :astronomical_item_id, value: @astronomical_item.id %>
    <br>
    <br>
    <%= f.submit :class => "btn btn-primary btn-sm" %>

<% end %>

app/views/search/_form.html.erb
<div>
<%= search_form_for(@query, url: search_path, :class => "d-flex search_bar") do |f| %>
    <%= f.search_field :name_or_category_or_user_name_i_cont_any, placeholder: "Venus...", :class => "form-control me-2" %>
    <%= f.submit "Search Catalogue", :class => "btn btn-primary" %>
<% end %>
</div>

app/views/search/index.html.erb
<h1><%= pluralize(@astronomical_items.count, "Result") %> </h1>

<div class="table">
    <table class="table table-dark table-striped">
        <thead>
            <th class="table_head"><%= sort_link(@query, :name, "Object Name", default_order: :asc)%></th>
            <th class="table_head"><%= sort_link(@query, :category, "Category") %></th>
            <th class="table_head">Author</th>
        </thead>

        <tbody>
            <% @astronomical_items.each do |astronomical_item| %>
                <tr>
                    <td> <%= link_to astronomical_item.name, astronomical_item %></td>
                    <td> <%= astronomical_item.category %> </td>
                    <td> <%= astronomical_item.user.name %> </td>
                </tr>
            <% end %>
        </tbody>
    </table>
</div>

app/views/session/new.html.erb
<h1>Sign in</h1>

<% if flash[:error].present? %>
    <p class="flash_login_error"><%= flash[:error] %></p>
<% end %>

<div class="mb-3"> 
<%= form_for login_path do %>

    <%= label_tag :email, nil, :class => 'form-label' %>
    <%= email_field_tag :email, nil, :class => 'form-control' %>

    <%= label_tag :password, nil, :class => 'form-label' %>
    <%= password_field_tag :password, nil, :class => 'form-control' %>
    <br>
    <%= submit_tag "Sign in", :class => "btn btn-primary" %>

<% end %>
</div></div>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<div class="mb-3">
<%= form_for @user do |f| %>

<% if @user.errors.any? %>
    <div class="flash_login_error">
        <ul>
        <% @user.errors.full_messages.each do |error| %>
            <li><%= error %></li>
        <% end %>
        </ul>  
    </div> 
<% end %>

        <%= f.label :name, :class => "form-label" %>
        <%= f.text_field :name, :class => "form-control" %>

        <%= f.label :email, :class => "form-label" %>
        <%= f.email_field :email, :class => "form-control" %>

        <%= f.label :password, :class => "form-label" %>
        <%= f.password_field :password, :class => "form-control" %>

        <%= f.label :password_confirmation, :class => "form-label" %>
        <%= f.password_field :password_confirmation, :class => "form-control" %>
        <br>
        <%= f.submit :class => "btn btn-primary" %>
    
<% end %>
</div>