config/routes.rb
Rails.application.routes.draw do

  root :to => "pages#about"
  get 'search', :to => "search#index"
  get '/astronomycatalogue/your_catalogue' => 'astronomical_items#author_index'
  resources :astronomical_items, path: :astronomycatalogue do 
    resources :comments, :only => [:create, :destroy ]
  end
  
  
  resources :users, :only => [:new, :create ]
  

  get '/bookmarks' => 'bookmarks#show'
  post '/bookmarks' => 'bookmarks#new'

  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/login' => 'session#destroy'
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/astronomical_item.rb
class AstronomicalItem < ApplicationRecord
    belongs_to :user, :optional => true
    has_many :bookmarks, :dependent => :destroy
    has_many :comments, :dependent => :destroy
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
    belongs_to :user, :optional => true #REMOVE LATER #use dependant destroy here?
    belongs_to :astronomical_item, :optional => true #REMOVE LATER
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :user, :optional => true #REMOVE LATER
    belongs_to :astronomical_item, :optional => true #REMOVE LATER
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password #research this
    validates :email, :uniqueness => true, :presence => true #research this
    
    has_many :astronomical_items
    has_many :bookmarks, :dependent => :destroy
    has_many :comments, :dependent => :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    before_action :fetch_user
    before_action :set_query

    def set_query
        @query = AstronomicalItem.ransack(params[:q])
    end


    private
    def fetch_user
        @current_user = User.find_by :id => session[:user_id]
        session[:user_id] = nil unless @current_user.present?
    end

    def check_for_login
        redirect_to login_path unless @current_user.present?
    end

    def bookmark_text
        if @bookmark_exists
            return "Remove Bookmark"
        else
            return "Bookmark"
        end
    end

    helper_method :bookmark_text

end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController

    before_action :check_for_login

    def show
        @bookmarked_astronomical_items = []
        @current_user.bookmarks.each do |bookmark|
            @bookmarked_astronomical_items.push(AstronomicalItem.find bookmark.astronomical_item_id)
        end
    end
        
    def new
        bookmark_check = Bookmark.find_by user_id: @current_user.id, astronomical_item_id: params[:astronomical_item_id]
        
        if bookmark_check.nil?
            bookmark = Bookmark.create(:user_id => @current_user.id, :astronomical_item_id => params[:astronomical_item_id])
            @bookmark_exists = true
        else
            bookmark_check.delete
            @bookmark_exists = false
        end
    end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

    def create
        comment = Comment.new comment_params
        if !comment.save
            flash[:notice] = comment.errors.full_messages.to_sentence
        
        end
        redirect_to astronomical_item_path(params[:astronomical_item_id])
    end

    def destroy
        comment = Comment.find params[:astronomical_item_id]
        comment.destroy
        redirect_to astronomical_item_path(params[:id])
    end


    private
    def comment_params
        params.require(:comment).permit(:content, :user_id, :astronomical_item_id )
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

    require 'httparty'

    def about
        @response = HTTParty.get('https://api.nasa.gov/planetary/apod?api_key=cuxOmwpr2KanSuHRAl75GBqxEWjLLqkYA9kBGqj4');
    end

end

app/controllers/search_controller.rb
class SearchController < ApplicationController

  def index
    @query = AstronomicalItem.ransack(params[:q])
    @astronomical_items = @query.result(distinct: true)
  end

end

app/controllers/session_controller.rb
class SessionController < ApplicationController


    def new
    end

    def create
        user = User.find_by :email => params[:email]
        if user.present? && user.authenticate(params[:password])
            session[:user_id] = user.id
            redirect_to root_path
        else
            flash[:error] = "Invalid email or password"
            redirect_to login_path
        end
    end

    def destroy
        session[:user_id] = nil
        redirect_to login_path
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new params_user
    if @user.save
      session[:user_id] = @user.id # add notice for successful creation
      redirect_to root_path
    else
      render :new
    end
  end

  private
  def params_user
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/astronomical_item_helper.rb
module AstronomicalItemHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Astronomy Catalouge</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= cloudinary_js_config %>
  </head>

  <body>
    <div class="container">

      
        <nav>
          <ol class="nav justify-content-center">
              <li class="nav-item">
                <%= link_to 'About', root_path, :class => "nav-link active" %>
              </li> 
            <% if @current_user.present? %>
              <li class="nav-item">
                <%= link_to "Add to Database", new_astronomical_item_path, :class => "nav-link active" %>
              </li>
              <li class="nav-item">
                <%= link_to "All Objects", astronomical_items_path, :class => "nav-link active" %>
              </li> 
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">Profile</a>
                <ul class="dropdown-menu">
                  <li><%= link_to "My Objects", astronomycatalogue_your_catalogue_path, :class => "dropdown-item" %></li>
                  <li><%= link_to "My Bookmarks", bookmarks_path, :class => "dropdown-item" %></li>
                  <li><hr class="dropdown-divider"></li>
                  <li><%= link_to "Sign out", login_path, :method => :delete, :class => "nav-link active" %></li>
                </ul>
              </li>
              
              <%= render :partial => "search/form"%>
              
            <% else %>
              <li class="nav-item">
                <%= link_to "Sign Up", new_user_path, :class => "nav-link active" %>
              </li>
              <li class="nav-item">
                <%= link_to "Sign in", login_path, :class => "nav-link active"  %>
              </li>
            <% end %> 
            </ol> 
        </nav>
      
      <%= yield %>

    </div>
  </body>
</html>

        

app/views/pages/about.html.erb
<h1><u>The Astronomy Catalogue</u></h1>

<div class="intro">
    <p>Welcome to the Astronomy Catalogue. Here amateur astronomers can add to a growing database of astronomical objects that they have observed or simply have an interest in.</p>

    <p>Users can search the catalogue for objects already in the database, bookmark objects, and view all objects they have added.</p>

    <p>Thank you for using the catalogue!</p>
</div>

<h2><u>NASA's Picture of the Day</u></h2>
<br>
<%= image_tag @response["url"], :class => 'feature' %>
<br>
<p class="explanation"><%= @response["copyright"] %> <%= @response["date"] %> <br><br>Courtesy of NASA's Astronomy Picture of the Day API </p>
<br>
<p class="explanation" ><u>Explanation:</u> <%= @response["explanation"] %></p>